apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: shop
  labels:
    app: chat-service
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: chat-service
