apiVersion: v1
kind: ConfigMap
metadata:
  name: rasa-service-config
  namespace: shop
  labels:
    app: rasa-service
data:
  APP_ENV: "production"
  PORT: "8000"
  USE_RASA: "false"
  PRODUCT_SERVICE_URL: "http://product-service.shop.svc.cluster.local"
  ORDER_SERVICE_URL: "http://order-service.shop.svc.cluster.local"
  API_GATEWAY_URL: "http://api-gateway.shop.svc.cluster.local"
