apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: shop
  labels:
    app: notification-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    name: http
  selector:
    app: notification-service
