apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: shop
  labels:
    app: product-service
data:
  APP_ENV: "production"
  PORT: "8080"
  LOG_LEVEL: "info"
  DB_HOST: "postgres.infra.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "product_db"
  DB_USER: "shopcaovanson"
  DB_SSLMODE: "disable"
  MONGO_HOST: "mongodb.infra.svc.cluster.local"
  MONGO_PORT: "27017"
  MONGO_USER: "shopcaovanson"
  MONGO_DB: "product_db"
  MONGO_AUTH_SOURCE: "admin"
  ELASTICSEARCH_URL: "http://elasticsearch.infra.svc.cluster.local:9200"
  ELASTICSEARCH_INDEX: "products"
  KAFKA_BROKERS: "kafka.infra.svc.cluster.local:9092"
  KAFKA_TOPIC_PRODUCT_CREATED: "product.created"
  KAFKA_TOPIC_PRODUCT_UPDATED: "product.updated"
  SEARCH_SERVICE_URL: "http://search-service.shop.svc.cluster.local"
