apiVersion: v1
kind: ConfigMap
metadata:
  name: caro-service-config
  namespace: shop
  labels:
    app: caro-service
data:
  PORT: "8087"
  DB_HOST: "postgres.infra.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "caro_db"
  DB_USER: "shopcaovanson"
  DB_SSLMODE: "disable"
  CORS_ORIGINS: "https://shopcaovanson.xyz,https://www.shopcaovanson.xyz,https://vocabee.cloud,http://localhost:3000"
  TURN_URL: "turn:vocabee.cloud:3478"
  TURN_USERNAME: "caro"
