apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: shop
  labels:
    app: auth-service
data:
  APP_ENV: "production"
  PORT: "8080"
  LOG_LEVEL: "info"
  DB_HOST: "postgres.infra.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "auth_db"
  DB_USER: "shopcaovanson"
  DB_SSLMODE: "disable"
  REDIS_HOST: "redis.infra.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  KAFKA_BROKERS: "kafka.infra.svc.cluster.local:9092"
  JWT_ACCESS_TTL_MINUTES: "15"
  JWT_REFRESH_TTL_DAYS: "7"
  KAFKA_TOPIC_USER_REGISTERED: "user.registered"
