ALTER TABLE orders DROP COLUMN IF EXISTS subtotal_amount;
ALTER TABLE orders DROP COLUMN IF EXISTS discount_amount;
ALTER TABLE orders DROP COLUMN IF EXISTS coupon_code;
DROP TABLE IF EXISTS coupons;
