apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: shop
  labels:
    app: order-service
data:
  APP_ENV: "production"
  PORT: "8080"
  LOG_LEVEL: "info"
  DB_HOST: "postgres.infra.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "order_db"
  DB_USER: "shopcaovanson"
  DB_SSLMODE: "disable"
  REDIS_HOST: "redis.infra.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "1"
  KAFKA_BROKERS: "kafka.infra.svc.cluster.local:9092"
  KAFKA_TOPIC_ORDER_CREATED: "order.created"
  PRODUCT_SERVICE_URL: "http://product-service.shop.svc.cluster.local"
  CART_TTL_DAYS: "30"
