apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: shop
  labels:
    app: api-gateway
data:
  APP_ENV: "production"
  PORT: "8080"
  LOG_LEVEL: "info"
  CORS_ORIGIN: "https://shopcaovanson.xyz"
  RATE_LIMIT_RPM: "100"
  AUTH_SERVICE_URL: "http://auth-service.shop.svc.cluster.local"
  PRODUCT_SERVICE_URL: "http://product-service.shop.svc.cluster.local"
  ORDER_SERVICE_URL: "http://order-service.shop.svc.cluster.local"
  CHAT_SERVICE_URL: "http://chat-service.shop.svc.cluster.local"
  REDIS_HOST: "redis.infra.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
