apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: shop
  labels:
    app: frontend
data:
  NUXT_PUBLIC_API_URL: "https://vocabee.cloud"
  NUXT_PUBLIC_WS_URL: "wss://vocabee.cloud"
