apiVersion: v1
kind: ConfigMap
metadata:
  name: search-service-config
  namespace: shop
  labels:
    app: search-service
data:
  APP_ENV: "production"
  PORT: "8000"
  LOG_LEVEL: "info"
  KAFKA_BROKERS: "kafka.infra.svc.cluster.local:9092"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.infra.svc.cluster.local:9092"
  KAFKA_GROUP_ID: "search-service"
  KAFKA_TOPIC_PRODUCT_CREATED: "product.created"
  KAFKA_TOPIC_PRODUCT_UPDATED: "product.updated"
  ELASTICSEARCH_INDEX: "products"
